# Generated by Django 2.1.3 on 2019-11-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='ted',
            field=models.CharField(default='sldkj', max_length=255),
            preserve_default=False,
        ),
    ]
