# Generated by Django 2.1.3 on 2019-11-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_audio_ted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='ted',
            field=models.TextField(max_length=255),
        ),
    ]
