# Generated by Django 2.1.3 on 2019-11-01 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20191101_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='ted',
        ),
        migrations.AddField(
            model_name='audio',
            name='annotator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audio',
            name='transcribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audio',
            name='transcription',
            field=models.TextField(blank=True),
        ),
    ]
