# Generated by Django 2.1.3 on 2019-11-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_charset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charset',
            name='data',
            field=models.TextField(default="()'aA-àÀ?âÂ,bB.cC;çÇ:dD!eEéÉèÈêÊëfFgGhHiIîÎïjJkKlLmMnNoOôÔpPqQrRsStTuUùûvVwWxXyYzZ ", null=True),
        ),
    ]
