# Generated by Django 2.1.3 on 2019-11-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191103_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
